# Generated by Django 5.1.7 on 2025-03-20 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_transaction_notes_remove_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlimit',
            name='company',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_limits', to='bank.company'),

        ),
    ]
