# Generated by Django 5.1.7 on 2025-03-20 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_userlimit_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='used_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='userlimit',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_limits', to='bank.company'),
        ),
    ]
