# Generated by Django 5.1.7 on 2025-03-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_company_used_amount_alter_userlimit_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='company',
            name='used_amount',
        ),
        migrations.RemoveField(
            model_name='userlimit',
            name='used_amount',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
