# Generated by Django 5.1.6 on 2025-03-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_remove_company_available_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlimit',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
