# Generated by Django 5.1.6 on 2025-03-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_company_created_at_balancehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
    ]
