# Generated by Django 5.1.6 on 2025-03-21 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_remove_company_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('max_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='bank.company')),
            ],
        ),
        migrations.DeleteModel(
            name='UserLimit',
        ),
    ]
