# Generated by Django 5.1.6 on 2025-03-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancehistory',
            old_name='amount_changed',
            new_name='transaction_amount',
        ),
    ]
