# Generated by Django 5.1.6 on 2025-03-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
